
project_id = "xwkzvcgymbelwuiqifgy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[functions.enhanced-bamabot]
verify_jwt = false

[functions.ai-agent-orchestrator]
verify_jwt = false

[edge_runtime]
enabled = true
port = 54327

[[env.supabase_url]]
name = "SUPABASE_URL"
value = "https://xwkzvcgymbelwuiqifgy.supabase.co"

[[env.supabase_anon_key]]
name = "SUPABASE_ANON_KEY"
value = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3a3p2Y2d5bWJlbHd1aXFpZmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjQyNzAsImV4cCI6MjA2NTM0MDI3MH0.px-YCUhJwImfJqngX1mMZEZqL22Butn0ajragC7JLrE"
