
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Search, TrendingUp, Zap, Filter } from 'lucide-react';
import BlogCard from '@/components/blog/BlogCard';
import BlogPost from '@/components/blog/BlogPost';
import TheScribe from '@/components/ai/TheScribe';
import SEO from '@/components/seo/SEO';
import Header from '@/components/sections/Header';
import Footer from '@/components/sections/Footer';
import { BlogPost as BlogPostType } from '@/types/blog';

const Blog = () => {
  const [selectedPost, setSelectedPost] = useState<BlogPostType | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [showScribe, setShowScribe] = useState(false);

  // Sample blog posts - in a real app, these would come from a database
  const samplePosts: BlogPostType[] = [
    {
      id: '1',
      title: 'Market Pulse: Machine Learning Engineers in High Demand Across Alabama',
      content: `# Market Pulse: Machine Learning Engineers in High Demand Across Alabama

Our latest data analysis reveals a significant 25% increase in demand for Machine Learning Engineers across Alabama this quarter, with the growth primarily concentrated in the Birmingham and Huntsville metro areas.

## Key Findings

- **25% increase** in ML engineer job postings
- **Birmingham leads** with 40% of new opportunities
- **Healthcare AI** driving the majority of hiring
- **Average salary range** increased to $85K-$120K

## Regional Breakdown

The growth is being driven by advancements in the financial services sector in Birmingham and the aerospace industry in Huntsville. This trend aligns with Alabama's strategic investments in AI education and research infrastructure.

## What This Means for Job Seekers

For professionals looking to enter the AI field, now is an excellent time to focus on machine learning skills. The combination of strong demand and competitive salaries makes Alabama an attractive destination for AI talent.

*This report was automatically generated by The Scribe based on real-time data from the BamaAI Connect platform.*`,
      excerpt: 'Our latest data shows a 25% jump in demand for Machine Learning Engineers across Alabama, driven by healthcare AI and financial services.',
      author: 'The Scribe',
      category: 'Market Pulse',
      tags: ['Machine Learning', 'Jobs', 'Alabama', 'Market Trends'],
      published_at: '2025-06-14T10:00:00Z',
      updated_at: '2025-06-14T10:00:00Z',
      status: 'published',
      metadata: {
        auto_generated: true,
        data_source: 'job_analytics',
      },
      read_time_minutes: 4
    },
    {
      id: '2',
      title: 'Spotlight: Welcoming QuantumLeap Analytics to the BamaAI Ecosystem',
      content: `# Spotlight: Welcoming QuantumLeap Analytics to the BamaAI Ecosystem

We're excited to highlight QuantumLeap Analytics, a promising new addition to Alabama's growing artificial intelligence community, specializing in predictive analytics for logistics and supply chain optimization.

## Company Overview

**Location**: Birmingham, Alabama
**Specialty**: Predictive Analytics & Supply Chain AI
**Founded**: 2024
**Team Size**: 12 employees

QuantumLeap Analytics is developing cutting-edge machine learning models that help logistics companies optimize their delivery routes, predict demand fluctuations, and reduce operational costs by up to 30%.

## Innovation Focus

The company's proprietary algorithms combine real-time traffic data, weather patterns, and historical delivery information to create dynamic routing solutions. Their recent pilot program with a major Alabama-based logistics company resulted in:

- 22% reduction in fuel costs
- 18% improvement in on-time deliveries
- 15% increase in customer satisfaction

## Leadership Team

Founded by former engineers from major tech companies, QuantumLeap brings both startup agility and enterprise experience to the Alabama AI landscape.

## Get Connected

Interested in learning more about QuantumLeap Analytics? Visit their full profile on our platform or explore similar companies in the Logistics AI category.

*This spotlight was automatically generated by The Scribe and reviewed by our editorial team.*`,
      excerpt: 'Meet QuantumLeap Analytics, a Birmingham-based startup revolutionizing logistics with predictive analytics and achieving 30% cost reductions for clients.',
      author: 'The Scribe',
      category: 'New Innovator',
      tags: ['Logistics', 'Predictive Analytics', 'Birmingham', 'Startup'],
      published_at: '2025-06-13T14:30:00Z',
      updated_at: '2025-06-13T14:30:00Z',
      status: 'published',
      metadata: {
        auto_generated: true,
        business_id: 1,
      },
      read_time_minutes: 3
    },
    {
      id: '3',
      title: 'Alabama AI Funding Roundup: $12M Raised Across Three Companies This Week',
      content: `# Alabama AI Funding Roundup: Week of June 14, 2025

This week's funding activity in Alabama's AI sector demonstrates continued investor confidence, with three companies announcing a combined $12 million in new capital.

## Funding Highlights

**MedAI Solutions** - $7M Series A
Birmingham-based medical imaging AI company raised $7 million to expand their diagnostic platform for radiology departments.

**AgriTech Innovations** - $3M Seed Round
Huntsville startup developing precision agriculture AI secured $3 million to scale their crop optimization technology.

**FinanceAI Labs** - $2M Pre-Seed
Montgomery-based fintech AI company raised $2 million for fraud detection and risk assessment tools.

## Investment Trends

This week's funding reflects key strengths in Alabama's AI ecosystem:

- **Healthcare AI** continues to attract significant investment
- **Agricultural technology** gaining momentum with precision farming focus
- **Financial services AI** emerging as a growth area

## Investor Landscape

The rounds were led by a mix of regional and national investors, including:
- Alabama Innovation Fund (lead investor in 2 rounds)
- Nashville-based healthcare VC
- Agricultural technology specialists from Texas

## Market Impact

The $12 million in funding represents a 40% increase compared to the same week last year, indicating sustained growth momentum in Alabama's AI investment landscape.

*This roundup was compiled by The Scribe from public sources and platform data.*`,
      excerpt: 'Three Alabama AI companies raised $12M this week, with healthcare AI leading the funding rounds and agricultural tech gaining momentum.',
      author: 'The Scribe',
      category: 'Funding Roundup',
      tags: ['Funding', 'Investment', 'Healthcare AI', 'AgTech'],
      published_at: '2025-06-12T09:00:00Z',
      updated_at: '2025-06-12T09:00:00Z',
      status: 'published',
      metadata: {
        auto_generated: true,
        funding_amount: 12000000,
      },
      read_time_minutes: 5
    }
  ];

  const categories = ['all', 'Market Pulse', 'New Innovator', 'Funding Roundup', 'AI Interview'];

  const filteredPosts = samplePosts.filter(post => {
    const matchesSearch = post.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         post.content.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         post.tags.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()));
    const matchesCategory = selectedCategory === 'all' || post.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  if (selectedPost) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-gray-700 to-gray-800">
        <SEO 
          title={selectedPost.title}
          description={selectedPost.excerpt}
        />
        <Header />
        <div className="container mx-auto px-6 py-8">
          <BlogPost 
            post={selectedPost} 
            onBack={() => setSelectedPost(null)} 
          />
        </div>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-700 to-gray-800">
      <SEO 
        title="BamaAI Insights"
        description="Stay informed with AI-generated insights, market analysis, and stories from Alabama's artificial intelligence ecosystem."
      />
      
      <Header />

      <div className="container mx-auto px-6 py-8">
        {/* Hero Section */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            BamaAI Insights
          </h1>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto mb-6">
            AI-generated insights, market analysis, and stories from Alabama's thriving artificial intelligence ecosystem.
          </p>
          <div className="flex items-center justify-center gap-2 mb-8">
            <Badge className="bg-purple-400/20 text-purple-400 px-4 py-2">
              🤖 Powered by The Scribe AI
            </Badge>
            <Badge variant="outline" className="text-gray-400 px-4 py-2">
              Real-time Data Insights
            </Badge>
          </div>
        </div>

        {/* Search and Filters */}
        <Card className="bg-gray-800 border-gray-700 mb-8">
          <CardContent className="p-6">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
                  <Input
                    placeholder="Search articles, topics, or companies..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-10 bg-gray-700 border-gray-600 text-white"
                  />
                </div>
              </div>
              <div className="flex gap-2 flex-wrap">
                {categories.map(category => (
                  <Button
                    key={category}
                    variant={selectedCategory === category ? "default" : "outline"}
                    size="sm"
                    onClick={() => setSelectedCategory(category)}
                    className={selectedCategory === category ? "bg-[#00C2FF] hover:bg-[#0099CC]" : ""}
                  >
                    {category === 'all' ? 'All' : category}
                  </Button>
                ))}
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowScribe(!showScribe)}
                className="flex items-center gap-2"
              >
                <Zap className="w-4 h-4" />
                The Scribe
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* The Scribe Interface */}
        {showScribe && (
          <div className="mb-8">
            <TheScribe />
          </div>
        )}

        {/* Blog Posts Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6 mb-8">
          {filteredPosts.map((post) => (
            <BlogCard
              key={post.id}
              post={post}
              onRead={setSelectedPost}
            />
          ))}
        </div>

        {filteredPosts.length === 0 && (
          <Card className="bg-gray-800 border-gray-700">
            <CardContent className="p-12 text-center">
              <div className="text-gray-400 mb-4">
                <Search className="w-12 h-12 mx-auto mb-4" />
                <h3 className="text-xl font-semibold mb-2">No articles found</h3>
                <p>Try adjusting your search terms or category filter.</p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Featured Content */}
        <Card className="bg-gradient-to-r from-purple-400/10 to-blue-400/10 border-purple-400/20 mt-12">
          <CardHeader>
            <CardTitle className="text-white flex items-center gap-2">
              <TrendingUp className="w-5 h-5" />
              About BamaAI Insights
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-300 mb-4">
              BamaAI Insights leverages our proprietary AI agent "The Scribe" to transform real-time ecosystem data 
              into compelling, readable content. Our automated content generation ensures you always have access to 
              the latest trends, company spotlights, and market analysis.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-gray-800/50 p-4 rounded-lg">
                <h4 className="font-semibold text-white mb-2">Market Pulse</h4>
                <p className="text-gray-400 text-sm">Weekly data-driven market analysis and trends</p>
              </div>
              <div className="bg-gray-800/50 p-4 rounded-lg">
                <h4 className="font-semibold text-white mb-2">Company Spotlights</h4>
                <p className="text-gray-400 text-sm">Automated profiles of new ecosystem members</p>
              </div>
              <div className="bg-gray-800/50 p-4 rounded-lg">
                <h4 className="font-semibold text-white mb-2">Funding Roundups</h4>
                <p className="text-gray-400 text-sm">Weekly investment and funding activity summaries</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Footer />
    </div>
  );
};

export default Blog;
