
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { FileText, Zap, TrendingUp, Users, DollarSign, MessageSquare } from 'lucide-react';
import { BlogPost, ContentTemplate, BlogGenerationRequest } from '@/types/blog';
import { useBusinesses } from '@/hooks/useBusinesses';

const TheScribe = () => {
  const [selectedTemplate, setSelectedTemplate] = useState<string>('');
  const [generatedContent, setGeneratedContent] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);
  const { data: businesses } = useBusinesses();

  const contentTemplates: ContentTemplate[] = [
    {
      id: 'market-pulse',
      name: 'Market Pulse Report',
      category: 'Market Pulse',
      template: 'Weekly data-driven market analysis',
      variables: ['metric', 'percentage_change', 'time_period', 'location'],
      auto_trigger_conditions: {
        data_threshold: 15, // 15% change triggers auto-generation
        time_interval: 'weekly'
      }
    },
    {
      id: 'new-innovator',
      name: 'New Innovator Spotlight',
      category: 'New Innovator',
      template: 'Welcome spotlight for new companies',
      variables: ['company_name', 'description', 'specialty', 'location'],
      auto_trigger_conditions: {
        business_criteria: ['verified', 'recent_addition']
      }
    },
    {
      id: 'funding-roundup',
      name: 'Funding Roundup',
      category: 'Funding Roundup',
      template: 'Weekly funding and investment digest',
      variables: ['total_amount', 'company_count', 'top_round'],
      auto_trigger_conditions: {
        time_interval: 'weekly'
      }
    }
  ];

  const generateContent = async (templateId: string) => {
    setIsGenerating(true);
    
    try {
      // Simulate AI content generation based on template and data
      const template = contentTemplates.find(t => t.id === templateId);
      if (!template) return;

      let content = '';
      
      switch (templateId) {
        case 'market-pulse':
          content = generateMarketPulseContent();
          break;
        case 'new-innovator':
          content = generateNewInnovatorContent();
          break;
        case 'funding-roundup':
          content = generateFundingRoundupContent();
          break;
        default:
          content = 'Generated content would appear here...';
      }
      
      setGeneratedContent(content);
    } catch (error) {
      console.error('Error generating content:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const generateMarketPulseContent = () => {
    const totalCompanies = businesses?.length || 0;
    const verifiedCompanies = businesses?.filter(b => b.verified).length || 0;
    const categories = [...new Set(businesses?.map(b => b.category).filter(Boolean))];
    
    return `# Market Pulse: Alabama AI Ecosystem Shows Strong Growth

Our latest data analysis reveals significant momentum in Alabama's artificial intelligence sector this quarter.

## Key Metrics

- **Total AI Companies**: ${totalCompanies} (up 12% from last quarter)
- **Verified Businesses**: ${verifiedCompanies} companies have completed our verification process
- **Active Categories**: ${categories.length} distinct AI specializations represented

## Regional Insights

The Birmingham and Huntsville metro areas continue to lead in AI innovation, with a notable increase in machine learning and healthcare AI startups. This growth aligns with Alabama's strategic investments in technology infrastructure and talent development.

## What This Means

The sustained growth in verified AI businesses indicates a maturing ecosystem with serious, committed players. For job seekers, this translates to expanding opportunities across ${categories.length} different specializations.

*This report was automatically generated by The Scribe based on real-time data from the BamaAI Connect platform.*`;
  };

  const generateNewInnovatorContent = () => {
    const recentBusiness = businesses?.find(b => b.verified) || businesses?.[0];
    if (!recentBusiness) return 'No recent businesses to spotlight.';

    return `# Spotlight: Welcoming ${recentBusiness.businessname} to the BamaAI Ecosystem

We're excited to highlight ${recentBusiness.businessname}, a new addition to Alabama's growing artificial intelligence community.

## Company Overview

**Location**: ${recentBusiness.location || 'Alabama'}
**Specialty**: ${recentBusiness.category || 'AI Solutions'}
**Founded**: ${recentBusiness.founded_year || 'Recently'}

${recentBusiness.description || 'This innovative company is bringing cutting-edge AI solutions to the Alabama market.'}

## What Sets Them Apart

${recentBusiness.businessname} joins a vibrant ecosystem of AI innovators across Alabama. Their focus on ${recentBusiness.category?.toLowerCase() || 'artificial intelligence'} adds valuable expertise to our growing community.

## Get Connected

Interested in learning more about ${recentBusiness.businessname}? [View their full profile](#) on our platform or explore similar companies in the ${recentBusiness.category || 'AI'} category.

*This spotlight was automatically generated by The Scribe and reviewed by our editorial team.*`;
  };

  const generateFundingRoundupContent = () => {
    return `# Alabama AI Funding Roundup: Week of ${new Date().toLocaleDateString()}

This week's funding activity in Alabama's AI sector shows continued investor confidence in the region's innovation potential.

## Funding Highlights

While specific funding announcements are currently being tracked, we're seeing increased investor interest in Alabama-based AI companies, particularly in the following sectors:

- **Healthcare AI**: Medical imaging and diagnostic tools
- **Agricultural Technology**: Precision farming and crop optimization
- **Manufacturing Intelligence**: Predictive maintenance and quality control
- **Financial Services**: Risk assessment and fraud detection

## Investment Trends

Alabama's strategic position as a technology hub continues to attract both regional and national investors. The combination of lower operational costs, strong university partnerships, and government support creates an attractive environment for AI startups.

## Looking Ahead

Our data suggests this positive funding momentum will continue, with several companies in our directory actively engaged in fundraising activities.

*This roundup was compiled by The Scribe from public sources and platform data.*`;
  };

  return (
    <div className="space-y-6">
      <Card className="bg-gray-800 border-gray-700">
        <CardHeader>
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-purple-400/10">
              <FileText className="w-6 h-6 text-purple-400" />
            </div>
            <div>
              <CardTitle className="text-white">The Scribe</CardTitle>
              <p className="text-gray-400 text-sm">AI Content & Storytelling Agent</p>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-gray-300">
            The Scribe transforms ecosystem data into compelling, readable content for BamaAI Insights. 
            Select a content template to generate data-driven articles automatically.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {contentTemplates.map((template) => (
              <Card 
                key={template.id} 
                className={`bg-gray-700 border-gray-600 cursor-pointer transition-colors hover:bg-gray-600 ${
                  selectedTemplate === template.id ? 'ring-2 ring-purple-400' : ''
                }`}
                onClick={() => setSelectedTemplate(template.id)}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <div className="p-2 rounded bg-purple-400/10">
                      {template.category === 'Market Pulse' && <TrendingUp className="w-4 h-4 text-purple-400" />}
                      {template.category === 'New Innovator' && <Users className="w-4 h-4 text-purple-400" />}
                      {template.category === 'Funding Roundup' && <DollarSign className="w-4 h-4 text-purple-400" />}
                    </div>
                    <div className="flex-1">
                      <h4 className="font-semibold text-white text-sm">{template.name}</h4>
                      <p className="text-gray-400 text-xs mt-1">{template.template}</p>
                      <Badge variant="secondary" className="mt-2 text-xs">
                        {template.category}
                      </Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="flex gap-3">
            <Button
              onClick={() => selectedTemplate && generateContent(selectedTemplate)}
              disabled={!selectedTemplate || isGenerating}
              className="bg-purple-600 hover:bg-purple-700"
            >
              <Zap className="w-4 h-4 mr-2" />
              {isGenerating ? 'Generating...' : 'Generate Content'}
            </Button>
          </div>

          {generatedContent && (
            <Card className="bg-gray-700 border-gray-600">
              <CardHeader>
                <CardTitle className="text-white text-lg">Generated Content Preview</CardTitle>
                <div className="flex items-center gap-2">
                  <Badge className="bg-purple-400/20 text-purple-400">By The Scribe</Badge>
                  <Badge variant="outline" className="text-gray-400">Auto-Generated</Badge>
                </div>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={generatedContent}
                  onChange={(e) => setGeneratedContent(e.target.value)}
                  className="min-h-[400px] bg-gray-800 border-gray-600 text-gray-300 font-mono text-sm"
                  placeholder="Generated content will appear here..."
                />
                <div className="flex gap-3 mt-4">
                  <Button variant="outline" size="sm">
                    Edit Content
                  </Button>
                  <Button size="sm" className="bg-green-600 hover:bg-green-700">
                    Publish to Blog
                  </Button>
                  <Button variant="outline" size="sm">
                    Save as Draft
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default TheScribe;
