// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwkzvcgymbelwuiqifgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3a3p2Y2d5bWJlbHd1aXFpZmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjQyNzAsImV4cCI6MjA2NTM0MDI3MH0.px-YCUhJwImfJqngX1mMZEZqL22Butn0ajragC7JLrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);